# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Radius
version:      1.56
version_from: version.pl
installdirs:  site
requires:
    Digest::MD5:                   0
    Test::More:                    0
    Test::Warn:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
